# Simple dict-based scorecard generator
import sys
sys.path.append('src')
import json
from pathlib import Path
import argparse


def write_json_deterministic(path, payload):
    """Write JSON with deterministic formatting for Phase 8 D2 compliance."""
    def normalize_floats(obj):
        if isinstance(obj, float):
            return round(obj, 6)
        elif isinstance(obj, dict):
            return {k: normalize_floats(v) for k, v in obj.items()}
        elif isinstance(obj, list):
            return [normalize_floats(item) for item in obj]
        else:
            return obj
    
    normalized_data = normalize_floats(payload)
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(normalized_data, f,
                 sort_keys=True,
                 indent=2,
                 ensure_ascii=False,
                 allow_nan=False)
        f.write('\n')

def generate_scorecards(analytics_file, out_dir, schema_version="8.1", verbose=False):
    # Load data as dict
    with open(analytics_file, 'r') as f:
        data = json.load(f)
    
    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)
    rulebooks_dir = out_path / "rulebooks"
    rulebooks_dir.mkdir(exist_ok=True)
    
    files_created = []
    
    for rb in data['rulebook_analytics']:
        rulebook_id = rb['identity']['rulebook_id']
        
        # Create simple scorecard
        scorecard = {
            'rulebook_id': rulebook_id,
            'source_pdf': rb['identity']['source_pdf_path'],
            'total_images': rb['extraction_outcome']['images_attempted'],
            'success_rate': rb['extraction_outcome']['success_rate'],
            'failure_rate': rb['extraction_outcome']['failure_rate'],
            'analytics_source': f"corpus_analytics.json -> rulebook_analytics[{rulebook_id}]",
            'schema_version': schema_version
        }

        # Add Phase 8 D2 fields for schema 8.2
        if schema_version == "8.2":
            scorecard['coverage_density'] = scorecard['success_rate']
            scorecard['classification_confidence_distribution'] = {'known_ratio': 1.0 - scorecard['failure_rate'], 'unknown_ratio': scorecard['failure_rate']}
            scorecard['component_type_entropy'] = 0.0
        
        # Write JSON
        json_file = rulebooks_dir / f"{rulebook_id}.json"
        write_json_deterministic(json_file, scorecard)
        files_created.append(json_file)
        
        # Write simple markdown
        md_content = f"""# QA Scorecard: {rulebook_id}

**Source PDF:** {scorecard['source_pdf']}

## Summary Metrics

| Metric | Value |
|--------|-------|
| Total Images | {scorecard['total_images']:,} |
| Success Rate | {scorecard['success_rate']:.1%} |
| Failure Rate | {scorecard['failure_rate']:.1%} |

## Evidence Anchors

- **Analytics Source:** {scorecard['analytics_source']}

---
*Generated by Hephaestus QA Scorecard Generator*
"""
        
        md_file = rulebooks_dir / f"{rulebook_id}.md"
        with open(md_file, 'w', encoding='utf-8') as f:
            f.write(md_content)
        files_created.append(md_file)
    
    return files_created

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Phase 8 Decision-Grade QA: Rulebook Scorecards")
    parser.add_argument("--analytics", required=True, help="Path to analytics directory or corpus_analytics.json")
    parser.add_argument("--out", required=True, help="Output directory for QA scorecards")
    parser.add_argument("--schema-version", choices=["8.1", "8.2"], default="8.1", help="QA scorecard schema version")
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")
    args = parser.parse_args()
    
    # Determine input file
    analytics_path = Path(args.analytics)
    if analytics_path.is_file() and analytics_path.name == "corpus_analytics.json":
        analytics_file = analytics_path
    elif analytics_path.is_dir():
        analytics_file = analytics_path / "corpus_analytics.json"
        if not analytics_file.exists():
            print(f"Error: corpus_analytics.json not found in {analytics_path}")
            sys.exit(1)
    else:
        print(f"Error: {analytics_path} must be a directory containing corpus_analytics.json or the file itself")
        sys.exit(1)
    
    if args.verbose:
        print(f"Loading analytics from: {analytics_file}")
    
    files = generate_scorecards(analytics_file, args.out, args.schema_version, args.verbose)
    print(f"Generated {len(files)} scorecard files in {args.out}")
    
    if args.verbose:
        for f in files:
            print(f"  {f}")
